name: macos
on:  
  workflow_dispatch:

      
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: view cpu
        run: |
          sysctl -n machdep.cpu.brand_string
          sw_vers
          df -h
          echo "CPU型号: $(sysctl -n machdep.cpu.brand_string)" && \
          echo "系统版本: $(sw_vers -productVersion)" && \
          echo "硬盘信息: $(diskutil info disk0 | grep 'Total Size')"
          
      - name: proxy 22
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo sysadminctl -addUser jiro -password zhangjl22222@ -admin
          sudo dscl . -append /Groups/admin GroupMembership jiro
          
          sudo wget https://github.com/ginuerzh/gost/releases/download/v2.12.0/gost_2.12.0_darwin_arm64.tar.gz
          sudo tar zxvf gost_2.12.0_darwin_arm64.tar.gz
          sudo chmod +x ./gost 
          # brew install gost
          ${{vars.GOST_SHELL_MACOS}}
          tail
