name: ubuntu
on:  
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook-lux
  push:  
    branches:  [ main ]
    paths:
      - 'urls.txt'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: proxy 22
        run: |
          wget https://github.com/ginuerzh/gost/releases/download/v2.11.5/gost-linux-amd64-2.11.5.gz
          gunzip gost-linux-amd64-2.11.5.gz && mv gost-linux-amd64-2.11.5 gost && chmod 777 gost
          useradd -s /bin/bash jiro && echo '123456' | passwd --stdin jiro
          ${{secrets.GOST_SHELL1}}
          tail
