name: ubuntu-armv7
on:  
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook-lux
  push:  
    branches:  [ main ]
    paths:
      - 'urls.txt'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: proxy 22
        with:
          arch: armv7
          distro: ubuntu22.04
        run: |
          sudo useradd -m -s /bin/bash jiro && echo 'jiro:zhangjl22222@' | sudo chpasswd
          sudo sh -c 'echo "jiro    ALL=(ALL:ALL) ALL" >> /etc/sudoers'
          wget https://github.com/verydemo/tools/releases/download/v0.1/gost.2.11.5.tar.gz
          tar zxvf gost.2.11.5.tar.gz && chmod 777 gost
          ${{secrets.GOST_SHELL1}}
          tail
